FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt --target /app/bin

COPY . .

FROM gcr.io/distroless/python3 AS Deployer

WORKDIR /app

COPY --from=builder /app/bin /app/bin

COPY --from=builder /app .

ENV PYTHONPATH="/app/bin"

CMD ["run.py"]


