name: Hello World

on:
  workflow_dispatch: 
    inputs:
     environments:
        type: choice
        options:
         - dev
         - prod
                 

jobs:
  greet:
     runs-on: ubuntu-latest
     steps:
        - name: Say hello to users
          run: echo "Hello Dost $USER"
       
  greet1:
      if: inputs.environments == 'prod'
      needs: [greet]
      runs-on: ubuntu-latest
      steps:
        - name: Say hello to ubuntu
          run: docker --version && python --version
