name: Hello World

on:
  workflow_dispatch: 

jobs:
  greet:
     runs-on: ubuntu-latest
     steps:
        - name: Say hello to users
          run: echo "Hello Dost $USER"
       
  greet1:
      runs-on: ubuntu-latest
      steps:
        - name: Say hello to ubuntu
          run: docker --version && python --version
